#!/usr/bin/env bash
set -euo pipefail

ROOT_PW="${MARIADB_ROOT_PASSWORD}"

DB_ADMIN_USER="${DB_ADMIN_USER}"
DB_ADMIN_PASSWORD="${DB_ADMIN_PASSWORD}"

DB_READONLY_USER="${DB_READONLY_USER}"
DB_READONLY_PASSWORD="${DB_READONLY_PASSWORD}"

mysql --protocol=socket -uroot -p"${ROOT_PW}" <<SQL
-- 平台级管理员账号（远程可用）
CREATE USER IF NOT EXISTS '${DB_ADMIN_USER}'@'%' IDENTIFIED BY '${DB_ADMIN_PASSWORD}';
GRANT ALL PRIVILEGES ON *.* TO '${DB_ADMIN_USER}'@'%' WITH GRANT OPTION;

-- 与 root 区分（防止等价）
REVOKE SUPER, SHUTDOWN, FILE ON *.* FROM '${DB_ADMIN_USER}'@'%';

-- 全库只读账号
CREATE USER IF NOT EXISTS '${DB_READONLY_USER}'@'%' IDENTIFIED BY '${DB_READONLY_PASSWORD}';
GRANT SELECT, SHOW VIEW ON *.* TO '${DB_READONLY_USER}'@'%';

FLUSH PRIVILEGES;
SQL
