#!/usr/bin/env bash
set -e

# v1.1.6 平台级账号初始化
# 仅在 MariaDB 首次初始化阶段执行
# 适配 MariaDB 11（使用 mariadb 客户端）

mariadb -uroot -p"${MARIADB_ROOT_PASSWORD}" <<SQL

-- 平台级管理员账号（DBA / 运维使用）
CREATE USER IF NOT EXISTS '${DB_ADMIN_USER}'@'%' IDENTIFIED BY '${DB_ADMIN_PASSWORD}';
GRANT
  SELECT, INSERT, UPDATE, DELETE,
  CREATE, DROP, INDEX, ALTER,
  CREATE TEMPORARY TABLES,
  EXECUTE,
  CREATE VIEW, SHOW VIEW,
  EVENT, TRIGGER
ON *.* TO '${DB_ADMIN_USER}'@'%' WITH GRANT OPTION;

-- 只读审计账号（查询 / 审计使用）
CREATE USER IF NOT EXISTS '${DB_READONLY_USER}'@'%' IDENTIFIED BY '${DB_READONLY_PASSWORD}';
GRANT
  SELECT, SHOW VIEW
ON *.* TO '${DB_READONLY_USER}'@'%';

FLUSH PRIVILEGES;
SQL
