services:
  init-perms:
    image: busybox:1.36
    command: sh -c 'mkdir -p /data && chmod 775 /data'
    volumes:
      - ./data:/data
    networks:
      - proxy
    restart: "no"

  mariadb:
    image: mariadb:11
    container_name: mariadb
    depends_on:
      init-perms:
        condition: service_completed_successfully
    env_file:
      - .env
    ports:
      - "${MARIADB_PORT:-3306}:3306"
    command:
      --max_allowed_packet=256M    #mariadb默认16MB，matomo建议用64MB
    volumes:
      - ./data:/var/lib/mysql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    external: true
